project_id = "ppllyabwoquacyuddacg"

[functions]
import_map = "./functions/import_map.json"

[functions."init-project"]
verify_jwt = false

[functions."validate-key"]
verify_jwt = false

[functions."get-sheet-info"]
verify_jwt = false

[functions."save-attributes"]
verify_jwt = false

[functions."get-attributes"]
verify_jwt = false

[functions."generate-survey-link"]
verify_jwt = false

[functions."load-survey"]
verify_jwt = false

[functions."submit-survey-response"]
verify_jwt = false

[functions."get-surveys"]
verify_jwt = false
